# Generated by Django 6.0.3 on 2026-03-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekers',
            name='desired_titles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='is_open_to_opportunities',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='preferred_locations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='work_mode',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
